# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node-browsers
    working_directory: ~/repo
    steps:
      - checkout

      # run tests!
      - run:
          name: run tests
          command: |
            bundle install --jobs=4 --retry=3
            ruby tests/test-server.rb